onEvent('jei.hide.items', event => {
  
  // Hides dusts
  event.hide('grinder:gold_dust')
  event.hide('grinder:iron_dust')
  event.hide('grinder:silver_dust')
  event.hide('grinder:copper_dust')
  event.hide('grinder:tin_dust')
  event.hide('grinder:nickel_dust')
  event.hide('grinder:lead_dust')
  event.hide('grinder:aluminum_dust')
  event.hide('grinder:uranium_dust')
  event.hide('grinder:zinc_dust')
  event.hide('grinder:platinum_dust')
  event.hide('grinder:mercury_dust')
  event.hide('grinder:bismuth_dust')
  event.hide('grinder:neptunium_dust')
  event.hide('grinder:osmium_dust')
  event.hide('grinder:cobalt_dust')
  event.hide('grinder:ardite_dust')
  event.hide('grinder:zitrite_dust')
  event.hide('grinder:rainbow_dust')
  event.hide('grinder:iesnium_dust')
  event.hide('grinder:starmetal_dust')
  event.hide('grinder:tungsten_dust')
  
  // Hides grindstones
//  event.hide('grinder:grindstone_stone')
//  event.hide('grinder:grindstone_granite')
//  event.hide('grinder:grindstone_diorite')
//  event.hide('grinder:grindstone_andesite')
//  event.hide('grinder:grindstone_iron')
//  event.hide('grinder:grindstone_gold')
//  event.hide('grinder:grindstone_diamond')
//  event.hide('grinder:grindstone_emerald')
//  event.hide('grinder:grindstone_obsidian')
  event.hide('grinder:grindstone_aluminum')
//  event.hide('grinder:grindstone_tin')
//  event.hide('grinder:grindstone_copper')
  event.hide('grinder:grindstone_nickel')
//  event.hide('grinder:grindstone_lead')
//  event.hide('grinder:grindstone_silver')
  event.hide('grinder:grindstone_platinum')
  event.hide('grinder:grindstone_mercury')
  event.hide('grinder:grindstone_zinc')
  event.hide('grinder:grindstone_bismuth')
  event.hide('grinder:grindstone_neptunium')
  event.hide('grinder:grindstone_uranium')
//  event.hide('grinder:grindstone_osmium')
  event.hide('grinder:grindstone_ardite')
  event.hide('grinder:grindstone_cobalt')
  event.hide('grinder:grindstone_zitrite')
  event.hide('grinder:grindstone_rainbow')
  event.hide('grinder:grindstone_starmetal')
  event.hide('grinder:grindstone_tungsten')
  event.hide('grinder:grindstone_iesnium')
})
